CONTIKI_PROJECT =  example-shell 
PROJECT_SOURCEFILES += symbols.c

all: $(CONTIKI_PROJECT)

APPS = serial-shell
CONTIKI = ../..
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV4 = 1
include $(CONTIKI)/Makefile.include
